networks:
  mos-network:
    driver: bridge

services:
  mos.db:
    container_name: mos-db
    image: postgres:16.4
    environment:
      POSTGRES_DB: mos-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5431:5432"
    networks:
      - mos-network
    volumes:
      - mos-db-data:/var/lib/postgresql/data
    
  mos.backend:
    container_name: mos-backend
    restart: unless-stopped
    build:
      context: ./MOSBackend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production #Development
      - ASPNETCORE_HTTP_PORTS=8080
      #- ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080"
    networks:
      - mos-network
    depends_on: 
      - mos.db
  
  mos.frontend:
    container_name: mos-frontend
    restart: unless-stopped
    build:
      context:  ./MOSFrontend
      dockerfile: Dockerfile
      args:
        VUE_APP_API_URL: http://localhost:8081
    ports:
      - "6981:80"
    networks:
      - mos-network
    depends_on: 
      - mos.backend

  mos.proxy:
    container_name: mos-proxy
    image: nginx:1.27.2-perl
    restart: always
    build:
      context: ./Proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Proxy/default.conf:/etc/nginx/conf.d/default.conf
      - cert-volume:/etc/letsencrypt/:ro
      - cert-www:/var/www/certbot:ro
    networks:
      - mos-network
    depends_on:
      - mos.frontend
      
volumes:
  mos-db-data:
  cert-volume: {}
  cert-www: {}

