version: "3.4"

networks:
  mos-network:
    driver: bridge

services:
  db:
    container_name: mos-db
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mos-db
    ports:
      - "5432:5432"
    networks:
      - mos-network
    #volumes:
    #  - postgres-data:/var/lib/postgresql/data
    
  #volumes:
  #  postgres-data:
    
  backend:
    container_name: mos-backend
    restart: unless-stopped
    build:
      context: ./MOSBackend
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development #Production
      - ASPNETCORE_HTTP_PORTS=8080
      #- ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080"
    networks:
      - mos-network
    depends_on: 
      - db
  
  frontend:
    container_name: mos-frontend
    restart: unless-stopped
    build:
      context:  ./MOSFrontend
      dockerfile: Dockerfile
      args:
        VUE_APP_API_URL: http://localhost:8080
    ports:
      - "8081:80"
    depends_on: 
      - backend

